const companies = [
 {name:"Mercado Exemplo Ltda.",cnpj:"12.345.678/0001-90",employees:42,device:"Autorizado",status:"Ativa"},
 {name:"Clínica Vida Mais",cnpj:"23.456.789/0001-01",employees:28,device:"Autorizado",status:"Ativa"},
 {name:"Distribuidora Central",cnpj:"34.567.890/0001-12",employees:17,device:"Pendente",status:"Ativa"},
 {name:"Hortifruti Modelo",cnpj:"45.678.901/0001-23",employees:36,device:"Autorizado",status:"Ativa"},
 {name:"Comercial do Bairro",cnpj:"56.789.012/0001-34",employees:11,device:"Revogado",status:"Atenção"}
];
const employees = [
 {name:"Mariana Alves",company:"Mercado Exemplo Ltda.",role:"Operadora de caixa",status:"Ativo"},
 {name:"Rafael Souza",company:"Clínica Vida Mais",role:"Recepcionista",status:"Ativo"},
 {name:"Camila Oliveira",company:"Distribuidora Central",role:"Auxiliar de estoque",status:"Ativo"},
 {name:"João Pedro Lima",company:"Hortifruti Modelo",role:"Repositor",status:"Ativo"},
 {name:"Ana Beatriz Costa",company:"Comercial do Bairro",role:"Atendente",status:"Ativo"},
 {name:"Lucas Martins",company:"Mercado Exemplo Ltda.",role:"Estoquista",status:"Ativo"}
];
const punches = [
 {name:"Mariana Alves",company:"Mercado Exemplo Ltda.",type:"Entrada",time:"08:02",status:"Recebida"},
 {name:"Rafael Souza",company:"Clínica Vida Mais",type:"Entrada",time:"08:04",status:"Recebida"},
 {name:"João Pedro Lima",company:"Hortifruti Modelo",type:"Retorno do intervalo",time:"13:01",status:"Recebida"},
 {name:"Camila Oliveira",company:"Distribuidora Central",type:"Entrada",time:"08:11",status:"Recebida"},
 {name:"Ana Beatriz Costa",company:"Comercial do Bairro",type:"Saída",time:"12:03",status:"Verificar"}
];
const state={view:"dashboard",company:"Isabelly"};
const $=s=>document.querySelector(s);
function toast(msg){const el=$("#toast");el.textContent=msg;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),3200)}
function heading(kicker,title,desc,action=""){return `<div class="page-heading"><div><p class="eyebrow">${kicker}</p><h1>${title}</h1><p>${desc}</p></div>${action}</div>`}
function stat(label,value,foot,icon){return `<div class="stat-card"><div class="stat-top"><span>${label}</span><span class="stat-icon">${icon}</span></div><div class="stat-value">${value}</div><div class="stat-foot">${foot}</div><span class="stat-arrow">›</span>${label==="Pendências"?'<span class="stat-alert">!</span>':""}</div>`}
function badge(text){let cls=text==="Recebida"||text==="Ativa"||text==="Autorizado"||text==="Ativo"?"ok":text==="Pendente"||text==="Verificar"||text==="Atenção"?"pending":text==="Revogado"?"error":"info";return `<span class="pill ${cls}">${text}</span>`}
function renderDashboard(){return `
<section class="welcome-banner"><div class="welcome-copy"><p class="eyebrow">PAINEL MASTER</p><h1>Olá, <span>${state.company}!</span> <span class="wave">👋</span></h1><p>Que bom ter você por aqui! Acompanhe tudo o que precisa,<br class="desktop-break"> de forma simples e organizada.</p></div><div class="welcome-art"><span class="welcome-script">Grandes resultados<br><b>são construídos com</b><br><em>gestão e pessoas.</em></span><div class="hero-monogram">P</div></div></section>
<div class="quick-actions">
<button class="quick-action" data-action="new-company"><span class="quick-icon">＋</span><span><strong>Novo projeto</strong><small>Cadastrar empresa</small></span><span class="quick-arrow">↗</span></button>
<button class="quick-action" data-action="new-employee"><span class="quick-icon">♟</span><span><strong>Adicionar funcionário</strong><small>Incluir colaborador</small></span><span class="quick-arrow">↗</span></button>
<button class="quick-action" data-view="clock"><span class="quick-icon">◷</span><span><strong>Lançar ponto</strong><small>Registrar jornada</small></span><span class="quick-arrow">↗</span></button>
<button class="quick-action" data-view="reports"><span class="quick-icon">▤</span><span><strong>Gerar relatório</strong><small>Ver e exportar</small></span><span class="quick-arrow">↗</span></button>
</div>
<div class="stats">${stat("Empresas cadastradas","05","<em>Ambiente de demonstração</em>","♟")}${stat("Funcionários ativos","134","Em todas as empresas demo","♙")}${stat("Marcações de hoje","128","Dados ilustrativos","◷")}${stat("Pendências","03","Dispositivos ou registros para revisar","▦")}</div>
<div class="two-col"><section class="panel"><div class="panel-heading"><div><h2>Últimas marcações</h2><p>Exemplo de registros recebidos pelo sistema</p></div><button class="text-link" data-view="records">Ver todas →</button></div><div class="record-list">${punches.slice(0,4).map(p=>`<div class="record"><div class="record-icon">${p.name.split(" ").map(x=>x[0]).slice(0,2).join("")}</div><div><div class="record-name">${p.name}</div><div class="record-meta">${p.company} · ${p.type}</div></div><div class="record-time">${p.time}</div>${badge(p.status)}</div>`).join("")}</div></section>
<section class="panel"><div class="panel-heading"><div><h2>Situação das empresas</h2><p>Resumo ilustrativo do cadastro</p></div><button class="text-link" data-view="companies">Ver todas →</button></div>${companies.slice(0,4).map((c,i)=>`<div class="bar-row"><div class="bar-label"><span>${c.name}</span><span>${c.employees} funcionários</span></div><div class="bar"><span style="width:${[88,62,45,72][i]}%"></span></div></div>`).join("")}<div class="notice"><div class="notice-icon">ⓘ</div><div><strong>Ambiente de demonstração</strong><p>Os números e registros desta tela são fictícios. Esta versão não salva nem valida marcações oficiais.</p></div></div></section></div>
<div class="dashboard-bottom"><section class="time-widget"><div class="time-copy"><span class="time-eyebrow">HOJE É</span><strong>20 de maio de 2026</strong><div class="live-time" id="dashboardClock">--:--</div><p>Organização hoje,<br>resultados amanhã.</p></div><div class="mini-calendar"><div class="calendar-title"><button data-action="calendar-prev" aria-label="Mês anterior">‹</button><strong>Maio 2026</strong><button data-action="calendar-next" aria-label="Próximo mês">›</button></div><div class="calendar-grid">${["D","S","T","Q","Q","S","S", "", "", "", "", "1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31"].map(d=>d?`<span class="${d==="20"?"today":""}">${d}</span>`:`<span class="blank"></span>`).join("")}</div></div></section>
<section class="panel shortcuts-panel"><div class="panel-heading"><div><h2>Acesso rápido</h2><p>Seus módulos mais utilizados</p></div></div><div class="shortcut-grid"><button data-view="employees"><span>♟</span><b>Funcionários</b><small>Gerenciar equipe</small></button><button data-view="companies"><span>▣</span><b>Empresas</b><small>Empresas e setores</small></button><button data-view="reports"><span>▤</span><b>Relatórios</b><small>Exportar dados</small></button><button data-view="settings"><span>⚙</span><b>Configurações</b><small>Personalizar sistema</small></button></div></section>
<section class="support-widget"><div><span>KR CONTÁBIL</span><h2>Organização também é <em>produtividade.</em></h2><p>Conte com a gente em cada etapa.</p><button data-action="support">♧ Suporte KR Contábil　›</button></div></section></div>`}
function renderCompanies(){return `${heading("CADASTRO","Empresas","Gerencie os clientes vinculados à KR Contábil.",'<button class="btn primary" data-action="new-company">＋ Nova empresa</button>')}<div class="table-panel"><div class="table-toolbar"><strong>Empresas cadastradas <span class="muted">(${companies.length})</span></strong><input class="search" id="searchTable" placeholder="Buscar por empresa ou CNPJ..." /></div><div class="table-wrap"><table id="dataTable"><thead><tr><th>EMPRESA</th><th>CNPJ</th><th>FUNCIONÁRIOS</th><th>DISPOSITIVO</th><th>STATUS</th><th>AÇÃO</th></tr></thead><tbody>${companies.map((c,i)=>`<tr><td><div class="company-cell"><div class="company-logo">${c.name[0]}</div><strong>${c.name}</strong></div></td><td>${c.cnpj}</td><td>${c.employees}</td><td>${badge(c.device)}</td><td>${badge(c.status)}</td><td><button class="text-link" data-action="company-detail" data-index="${i}">Gerenciar →</button></td></tr>`).join("")}</tbody></table></div></div>`}
function renderEmployees(){return `${heading("EQUIPE","Funcionários","Cadastros de demonstração vinculados às empresas.",'<button class="btn primary" data-action="new-employee">＋ Novo funcionário</button>')}<div class="table-panel"><div class="table-toolbar"><strong>Funcionários <span class="muted">(${employees.length})</span></strong><input class="search" id="searchTable" placeholder="Buscar por nome ou empresa..." /></div><div class="table-wrap"><table id="dataTable"><thead><tr><th>FUNCIONÁRIO</th><th>EMPRESA</th><th>CARGO</th><th>STATUS</th><th>AÇÃO</th></tr></thead><tbody>${employees.map((e,i)=>`<tr><td><strong>${e.name}</strong></td><td>${e.company}</td><td>${e.role}</td><td>${badge(e.status)}</td><td><button class="text-link" data-action="employee-detail" data-index="${i}">Ver perfil →</button></td></tr>`).join("")}</tbody></table></div></div>`}
function renderDevices(){return `${heading("DISPOSITIVOS","Celulares autorizados","Gerencie os celulares oficiais usados para registrar ponto.")}<div class="two-col"><section class="panel"><div class="panel-heading"><div><h2>Dispositivo principal</h2><p>Mercado Exemplo Ltda.</p></div>${badge("Autorizado")}</div><div class="device-card"><div class="device-illustration">▯</div><div class="device-detail"><h3>Celular da recepção</h3><p>Identificador: DEV-DEMO-001<br>Vinculado a: Mercado Exemplo Ltda.<br>Última sincronização: hoje, 13:18<br>Este é um registro ilustrativo, não um dispositivo realmente autenticado.</p><div class="device-actions"><button class="btn" data-action="device-info">Ver detalhes</button><button class="btn" data-action="revoke-device">Simular revogação</button></div></div></div></section><section class="panel"><div class="panel-heading"><div><h2>Solicitações</h2><p>Dispositivos que aguardam revisão</p></div>${badge("1 pendente")}</div><div class="record"><div class="record-icon">▯</div><div><div class="record-name">Distribuidora Central</div><div class="record-meta">Novo celular · Solicitado hoje</div></div><button class="btn" data-action="approve-device">Analisar</button></div><div class="notice"><div class="notice-icon">🔐</div><div><strong>Autorização segura</strong><p>No sistema real, a ativação exigirá autenticação e credencial de dispositivo. Esta demonstração não autoriza aparelhos.</p></div></div></section></div>`}
function renderRecords(){return `${heading("JORNADA","Marcações de ponto","Consulte os exemplos de marcações exibidos no painel.",'<button class="btn" data-action="export-demo">Exportar demonstração</button>')}<div class="table-panel"><div class="table-toolbar"><strong>Marcações recentes</strong><input class="search" id="searchTable" placeholder="Buscar funcionário ou empresa..." /></div><div class="table-wrap"><table id="dataTable"><thead><tr><th>FUNCIONÁRIO</th><th>EMPRESA</th><th>TIPO</th><th>HORÁRIO DEMO</th><th>STATUS</th></tr></thead><tbody>${punches.map(p=>`<tr><td><strong>${p.name}</strong></td><td>${p.company}</td><td>${p.type}</td><td>${p.time}</td><td>${badge(p.status)}</td></tr>`).join("")}</tbody></table></div></div><div class="notice"><div class="notice-icon">ⓘ</div><div><strong>Importante</strong><p>Esta página contém dados fictícios. Não use estes registros para apuração de folha ou como comprovante oficial de jornada.</p></div></div>`}
function renderReports(){return `${heading("DP E RELATÓRIOS","Relatórios","Prévia das ferramentas que serão implementadas na versão conectada.")}<div class="report-grid">${[["Espelho de ponto","Resumo individual por funcionário e competência.","▤"],["Pendências de marcação","Identifique dias com registros incompletos.","!"],["Resumo de jornada","Horas previstas e apuradas conforme regras configuradas.","◷"],["Relatório por empresa","Visão consolidada para conferência do DP.","▣"],["Auditoria","Histórico de solicitações e ações administrativas.","⌁"],["Exportação para folha","Preparação de dados para conferência e integração.","⇩"]].map((r,i)=>`<div class="report-card"><div class="stat-icon">${r[2]}</div><h3>${r[0]}</h3><p>${r[1]}</p><button class="btn" data-action="report" data-index="${i}">Visualizar módulo</button></div>`).join("")}</div>`}
function renderClock(){return `${heading("PWA DO FUNCIONÁRIO","Marcação de ponto","Prévia da tela para o celular oficial da empresa.")}<div class="clock-demo"><div class="clock-logo">P</div><h2 style="margin:0;font-size:18px">Ponto.com</h2><p class="muted" style="margin:6px 0">Mercado Exemplo Ltda. · Dispositivo de demonstração</p><div class="clock-time" id="clockTime">--:--:--</div><div class="clock-date" id="clockDate"></div><label for="pinInput" style="display:block;margin-top:20px;font-weight:700;font-size:12px">Identificação do funcionário</label><input class="pin-input" id="pinInput" inputmode="numeric" maxlength="6" placeholder="••••" aria-label="PIN de demonstração"><div class="clock-actions"><button class="btn primary" data-action="clock-in">Entrada</button><button class="btn" data-action="clock-break">Saída intervalo</button><button class="btn" data-action="clock-return">Retorno intervalo</button><button class="btn" data-action="clock-out">Saída final</button></div><div class="clock-warning">Modo demonstração: os botões não criam registros oficiais e não enviam dados ao servidor.</div></div>`}
function render(){const views={dashboard:renderDashboard,companies:renderCompanies,employees:renderEmployees,devices:renderDevices,records:renderRecords,reports:renderReports,clock:renderClock};const titles={dashboard:"Visão geral",companies:"Empresas",employees:"Funcionários",devices:"Dispositivos",records:"Marcações de ponto",reports:"Relatórios",clock:"PWA de marcação"};$("#content").innerHTML=(views[state.view]||renderDashboard)();const crumb=$("#pageCrumb");if(crumb)crumb.textContent=titles[state.view]||"Configurações";document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.view===state.view));$("#sidebar").classList.remove("open");const search=$("#searchTable");if(search)search.addEventListener("input",()=>{const q=search.value.toLowerCase();$("#dataTable").querySelectorAll("tbody tr").forEach(tr=>tr.style.display=tr.innerText.toLowerCase().includes(q)?"":"none")});if(state.view==="clock")updateClock()}
function updateClock(){const d=new Date();const t=$("#clockTime"),dt=$("#clockDate");if(t)t.textContent=d.toLocaleTimeString("pt-BR");if(dt)dt.textContent=d.toLocaleDateString("pt-BR",{weekday:"long",day:"2-digit",month:"long",year:"numeric"})}
document.addEventListener("click",e=>{const nav=e.target.closest("[data-view]");if(nav){state.view=nav.dataset.view;render();return}const b=e.target.closest("[data-action]");if(!b)return;const a=b.dataset.action;if(a==="new-company")toast("Na próxima etapa, este botão será ligado ao cadastro real de empresas.");else if(a==="new-employee")toast("Na próxima etapa, este botão será ligado ao cadastro de funcionários.");else if(a==="company-detail")toast("Detalhes de "+companies[+b.dataset.index].name+" — dados de demonstração.");else if(a==="employee-detail")toast("Perfil de "+employees[+b.dataset.index].name+" — dados de demonstração.");else if(a==="device-info")toast("Detalhes ilustrativos. Nenhum aparelho está realmente vinculado.");else if(a==="revoke-device")toast("Simulação: no sistema real, a revogação exigirá confirmação e ficará auditada.");else if(a==="approve-device")toast("Simulação: a autorização real será feita pela KR após validar o dispositivo.");else if(a==="export-demo")toast("Exportação indisponível nesta demonstração; nenhum dado real será exportado.");else if(a==="report")toast("Módulo em planejamento: "+["Espelho de ponto","Pendências de marcação","Resumo de jornada","Relatório por empresa","Auditoria","Exportação para folha"][+b.dataset.index]+".");else if(a.startsWith("clock-")){const pin=$("#pinInput")?.value||"";if(pin.length<4)toast("Digite uma identificação de demonstração com pelo menos 4 números.");else toast("Demonstração apenas: nenhuma marcação oficial foi criada.");}});
$("#nav").addEventListener("click",e=>{const b=e.target.closest("[data-view]");if(b){state.view=b.dataset.view;render()}});
$("#mobileMenu").addEventListener("click",()=>{const sidebar=$("#sidebar");if(window.matchMedia("(max-width: 760px)").matches){sidebar.classList.toggle("open")}else{document.querySelector(".app-shell").classList.toggle("sidebar-collapsed");$("#mobileMenu").setAttribute("aria-expanded",String(!document.querySelector(".app-shell").classList.contains("sidebar-collapsed")))}});
$("#profileButton").addEventListener("click",()=>toast("Perfil de demonstração: Isabelly Martins · DP - KR Contábil."));
$("#notificationsButton").addEventListener("click",()=>toast("Você tem 3 notificações ilustrativas para revisar."));
render();setInterval(updateClock,1000);
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));
